-- RK-Conecte / RK Vidracaria
-- Sprint 5.3 - Schema inicial para futura integracao MySQL.
-- Este script nao migra dados reais e nao substitui Firebase/localStorage.

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(160) NOT NULL,
    email VARCHAR(180) NULL,
    telefone VARCHAR(40) NULL,
    perfil VARCHAR(60) NOT NULL DEFAULT 'operador',
    status VARCHAR(40) NOT NULL DEFAULT 'ativo',
    firebase_uid VARCHAR(160) NULL,
    ultimo_login_em DATETIME NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_usuarios_email (email),
    UNIQUE KEY uk_usuarios_firebase_uid (firebase_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(180) NOT NULL,
    telefone VARCHAR(40) NULL,
    email VARCHAR(180) NULL,
    documento VARCHAR(40) NULL,
    endereco TEXT NULL,
    origem VARCHAR(80) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ativo',
    observacoes TEXT NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_clientes_nome (nome),
    KEY idx_clientes_telefone (telefone),
    KEY idx_clientes_email (email),
    UNIQUE KEY uk_clientes_id_firestore (id_firestore)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projetos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cliente_id BIGINT UNSIGNED NULL,
    responsavel_id BIGINT UNSIGNED NULL,
    numero VARCHAR(80) NULL,
    titulo VARCHAR(180) NOT NULL,
    status VARCHAR(60) NOT NULL DEFAULT 'rascunho',
    etapa VARCHAR(80) NULL,
    origem VARCHAR(80) NULL,
    endereco_obra TEXT NULL,
    previsao_inicio DATE NULL,
    previsao_entrega DATE NULL,
    valor_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    observacoes TEXT NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_projetos_cliente (cliente_id),
    KEY idx_projetos_status (status),
    KEY idx_projetos_responsavel (responsavel_id),
    UNIQUE KEY uk_projetos_id_firestore (id_firestore),
    CONSTRAINT fk_projetos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_projetos_responsavel FOREIGN KEY (responsavel_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orcamentos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cliente_id BIGINT UNSIGNED NULL,
    projeto_id BIGINT UNSIGNED NULL,
    vendedor_id BIGINT UNSIGNED NULL,
    numero VARCHAR(80) NULL,
    titulo VARCHAR(180) NULL,
    status VARCHAR(60) NOT NULL DEFAULT 'rascunho',
    validade DATE NULL,
    forma_pagamento VARCHAR(120) NULL,
    prazo_entrega VARCHAR(120) NULL,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    desconto_valor DECIMAL(12,2) NOT NULL DEFAULT 0,
    desconto_percentual DECIMAL(8,2) NOT NULL DEFAULT 0,
    acrescimo DECIMAL(12,2) NOT NULL DEFAULT 0,
    total DECIMAL(12,2) NOT NULL DEFAULT 0,
    observacoes TEXT NULL,
    origem VARCHAR(80) NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_orcamentos_cliente (cliente_id),
    KEY idx_orcamentos_projeto (projeto_id),
    KEY idx_orcamentos_status (status),
    KEY idx_orcamentos_numero (numero),
    UNIQUE KEY uk_orcamentos_id_firestore (id_firestore),
    CONSTRAINT fk_orcamentos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_orcamentos_projeto FOREIGN KEY (projeto_id) REFERENCES projetos (id) ON DELETE SET NULL,
    CONSTRAINT fk_orcamentos_vendedor FOREIGN KEY (vendedor_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orcamento_itens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    orcamento_id BIGINT UNSIGNED NOT NULL,
    ordem INT UNSIGNED NOT NULL DEFAULT 1,
    descricao VARCHAR(255) NOT NULL,
    grupo_servico VARCHAR(100) NULL,
    tipo VARCHAR(100) NULL,
    subtipo VARCHAR(120) NULL,
    produto_nome VARCHAR(160) NULL,
    largura_cm DECIMAL(10,2) NOT NULL DEFAULT 0,
    altura_cm DECIMAL(10,2) NOT NULL DEFAULT 0,
    area_m2 DECIMAL(10,4) NOT NULL DEFAULT 0,
    quantidade DECIMAL(10,2) NOT NULL DEFAULT 1,
    unidade VARCHAR(40) NOT NULL DEFAULT 'un',
    valor_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
    adicional_engenharia DECIMAL(12,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    observacoes TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_orcamento_itens_orcamento (orcamento_id),
    CONSTRAINT fk_orcamento_itens_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS caixa_lancamentos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cliente_id BIGINT UNSIGNED NULL,
    orcamento_id BIGINT UNSIGNED NULL,
    usuario_id BIGINT UNSIGNED NULL,
    descricao VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NULL,
    tipo VARCHAR(30) NOT NULL,
    valor DECIMAL(12,2) NOT NULL DEFAULT 0,
    data_lancamento DATE NOT NULL,
    forma_pagamento VARCHAR(100) NULL,
    origem VARCHAR(100) NULL,
    observacao TEXT NULL,
    responsavel VARCHAR(160) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'confirmado',
    mes_referencia VARCHAR(7) NULL,
    ano_referencia INT NULL,
    dia_referencia INT NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    schema_version INT NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em_iso VARCHAR(40) NULL,
    atualizado_em_iso VARCHAR(40) NULL,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_caixa_data (data_lancamento),
    KEY idx_caixa_tipo (tipo),
    KEY idx_caixa_status (status),
    KEY idx_caixa_cliente (cliente_id),
    KEY idx_caixa_orcamento (orcamento_id),
    UNIQUE KEY uk_caixa_id_firestore (id_firestore),
    CONSTRAINT fk_caixa_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_caixa_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos (id) ON DELETE SET NULL,
    CONSTRAINT fk_caixa_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agenda_eventos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cliente_id BIGINT UNSIGNED NULL,
    projeto_id BIGINT UNSIGNED NULL,
    usuario_id BIGINT UNSIGNED NULL,
    titulo VARCHAR(180) NOT NULL,
    tipo VARCHAR(80) NULL,
    status VARCHAR(60) NOT NULL DEFAULT 'agendado',
    data_inicio DATETIME NOT NULL,
    data_fim DATETIME NULL,
    local VARCHAR(255) NULL,
    observacoes TEXT NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_agenda_periodo (data_inicio, data_fim),
    KEY idx_agenda_projeto (projeto_id),
    KEY idx_agenda_cliente (cliente_id),
    UNIQUE KEY uk_agenda_id_firestore (id_firestore),
    CONSTRAINT fk_agenda_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_agenda_projeto FOREIGN KEY (projeto_id) REFERENCES projetos (id) ON DELETE SET NULL,
    CONSTRAINT fk_agenda_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pdfs_comerciais (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cliente_id BIGINT UNSIGNED NULL,
    projeto_id BIGINT UNSIGNED NULL,
    orcamento_id BIGINT UNSIGNED NULL,
    usuario_id BIGINT UNSIGNED NULL,
    titulo VARCHAR(180) NOT NULL,
    tipo VARCHAR(80) NOT NULL DEFAULT 'orcamento',
    status VARCHAR(60) NOT NULL DEFAULT 'gerado',
    arquivo_url TEXT NULL,
    storage_path TEXT NULL,
    hash_arquivo VARCHAR(160) NULL,
    versao VARCHAR(40) NULL,
    gerado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pdfs_cliente (cliente_id),
    KEY idx_pdfs_projeto (projeto_id),
    KEY idx_pdfs_orcamento (orcamento_id),
    CONSTRAINT fk_pdfs_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_pdfs_projeto FOREIGN KEY (projeto_id) REFERENCES projetos (id) ON DELETE SET NULL,
    CONSTRAINT fk_pdfs_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos (id) ON DELETE SET NULL,
    CONSTRAINT fk_pdfs_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ordens_producao (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    projeto_id BIGINT UNSIGNED NULL,
    cliente_id BIGINT UNSIGNED NULL,
    responsavel_id BIGINT UNSIGNED NULL,
    numero VARCHAR(80) NULL,
    status VARCHAR(60) NOT NULL DEFAULT 'PENDENTE',
    prioridade VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    descricao TEXT NULL,
    previsao_inicio DATE NULL,
    previsao_entrega DATE NULL,
    tempo_estimado_minutos INT UNSIGNED NULL,
    checklist_json JSON NULL,
    historico_json JSON NULL,
    observacoes TEXT NULL,
    id_local VARCHAR(120) NULL,
    id_firestore VARCHAR(160) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_ordens_projeto (projeto_id),
    KEY idx_ordens_cliente (cliente_id),
    KEY idx_ordens_status (status),
    KEY idx_ordens_prioridade (prioridade),
    UNIQUE KEY uk_ordens_id_firestore (id_firestore),
    CONSTRAINT fk_ordens_projeto FOREIGN KEY (projeto_id) REFERENCES projetos (id) ON DELETE SET NULL,
    CONSTRAINT fk_ordens_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL,
    CONSTRAINT fk_ordens_responsavel FOREIGN KEY (responsavel_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

